### Добавление задачи

POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Test task",
  "description": "Some description",
  "assignTo": "Max",
  "priority": "MEDIUM"
}


### Получение задачи

GET http://localhost:8080/api/tasks/1


### Получение списка задач

GET http://localhost:8080/api/tasks
